// Generated by: npm run supabase:remote-types
// Docs only — project uses plain JS (CJS).
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      attendances: {
        Row: {
          checked_in_at: string
          guild_id: string
          id: string
          late_minutes: number | null
          marked_by: string | null
          session_id: string
          status: string
          user_id: string
          username: string
        }
        Insert: {
          checked_in_at?: string
          guild_id: string
          id?: string
          late_minutes?: number | null
          marked_by?: string | null
          session_id: string
          status: string
          user_id: string
          username: string
        }
        Update: {
          checked_in_at?: string
          guild_id?: string
          id?: string
          late_minutes?: number | null
          marked_by?: string | null
          session_id?: string
          status?: string
          user_id?: string
          username?: string
        }
        Relationships: [
          {
            foreignKeyName: "attendances_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      badges: {
        Row: {
          created_at: string | null
          emoji: string
          guild_id: string
          id: number
          label: string
          threshold: number
        }
        Insert: {
          created_at?: string | null
          emoji?: string
          guild_id: string
          id?: number
          label: string
          threshold: number
        }
        Update: {
          created_at?: string | null
          emoji?: string
          guild_id?: string
          id?: number
          label?: string
          threshold?: number
        }
        Relationships: []
      }
      guild_configs: {
        Row: {
          admin_role_id: string | null
          admin_role_name: string | null
          allowed_role_id: string | null
          allowed_role_name: string | null
          attendance_role_id: string | null
          default_role_id: string | null
          guild_id: string
          log_channel_id: string | null
          notification_channel_id: string | null
          phai_role_icons: Json | null
          phai_role_ids: string[] | null
          reminder_enabled: boolean
          reminder_minutes: number
          timezone: string
          updated_at: string
        }
        Insert: {
          admin_role_id?: string | null
          admin_role_name?: string | null
          allowed_role_id?: string | null
          allowed_role_name?: string | null
          attendance_role_id?: string | null
          default_role_id?: string | null
          guild_id: string
          log_channel_id?: string | null
          notification_channel_id?: string | null
          phai_role_icons?: Json | null
          phai_role_ids?: string[] | null
          reminder_enabled?: boolean
          reminder_minutes?: number
          timezone?: string
          updated_at?: string
        }
        Update: {
          admin_role_id?: string | null
          admin_role_name?: string | null
          allowed_role_id?: string | null
          allowed_role_name?: string | null
          attendance_role_id?: string | null
          default_role_id?: string | null
          guild_id?: string
          log_channel_id?: string | null
          notification_channel_id?: string | null
          phai_role_icons?: Json | null
          phai_role_ids?: string[] | null
          reminder_enabled?: boolean
          reminder_minutes?: number
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      member_badges: {
        Row: {
          earned_at: string | null
          guild_id: string
          id: number
          threshold: number
          user_id: string
        }
        Insert: {
          earned_at?: string | null
          guild_id: string
          id?: number
          threshold: number
          user_id: string
        }
        Update: {
          earned_at?: string | null
          guild_id?: string
          id?: number
          threshold?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "member_badges_guild_threshold_fkey"
            columns: ["guild_id", "threshold"]
            isOneToOne: false
            referencedRelation: "badges"
            referencedColumns: ["guild_id", "threshold"]
          },
        ]
      }
      member_stats: {
        Row: {
          best_streak: number
          current_streak: number
          guild_id: string
          last_attended_at: string | null
          last_session_id: string | null
          total_absent: number
          total_excused: number
          total_joined: number
          total_late: number
          total_sessions: number
          updated_at: string
          user_id: string
        }
        Insert: {
          best_streak?: number
          current_streak?: number
          guild_id: string
          last_attended_at?: string | null
          last_session_id?: string | null
          total_absent?: number
          total_excused?: number
          total_joined?: number
          total_late?: number
          total_sessions?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          best_streak?: number
          current_streak?: number
          guild_id?: string
          last_attended_at?: string | null
          last_session_id?: string | null
          total_absent?: number
          total_excused?: number
          total_joined?: number
          total_late?: number
          total_sessions?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "member_stats_last_session_id_fkey"
            columns: ["last_session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      members: {
        Row: {
          ghi_chu: string | null
          guild_id: string
          id: number
          joined_at: string
          phong_ban: string | null
          updated_at: string
          user_id: string
          username: string | null
        }
        Insert: {
          ghi_chu?: string | null
          guild_id: string
          id?: number
          joined_at?: string
          phong_ban?: string | null
          updated_at?: string
          user_id: string
          username?: string | null
        }
        Update: {
          ghi_chu?: string | null
          guild_id?: string
          id?: number
          joined_at?: string
          phong_ban?: string | null
          updated_at?: string
          user_id?: string
          username?: string | null
        }
        Relationships: []
      }
      reminders: {
        Row: {
          due_at: string
          guild_id: string
          id: string
          message: string | null
          sent_at: string | null
        }
        Insert: {
          due_at: string
          guild_id: string
          id?: string
          message?: string | null
          sent_at?: string | null
        }
        Update: {
          due_at?: string
          guild_id?: string
          id?: string
          message?: string | null
          sent_at?: string | null
        }
        Relationships: []
      }
      scheduled_sessions: {
        Row: {
          allowed_role_id: string | null
          channel_id: string
          close_day_of_week: number | null
          close_hour: number | null
          close_minute: number | null
          created_at: string | null
          day_of_week: number
          guild_id: string
          hour: number
          id: string
          is_active: boolean
          minute: number
          phai_role_ids: string[]
          pre_close_minutes: number
          reminder_1_min: number
          reminder_2_min: number
          reminder_enabled: boolean
          reminder_minutes: number | null
          session_name: string
          skip_until: string | null
          updated_at: string
        }
        Insert: {
          allowed_role_id?: string | null
          channel_id: string
          close_day_of_week?: number | null
          close_hour?: number | null
          close_minute?: number | null
          created_at?: string | null
          day_of_week: number
          guild_id: string
          hour: number
          id?: string
          is_active?: boolean
          minute?: number
          phai_role_ids?: string[]
          pre_close_minutes?: number
          reminder_1_min?: number
          reminder_2_min?: number
          reminder_enabled?: boolean
          reminder_minutes?: number | null
          session_name: string
          skip_until?: string | null
          updated_at?: string
        }
        Update: {
          allowed_role_id?: string | null
          channel_id?: string
          close_day_of_week?: number | null
          close_hour?: number | null
          close_minute?: number | null
          created_at?: string | null
          day_of_week?: number
          guild_id?: string
          hour?: number
          id?: string
          is_active?: boolean
          minute?: number
          phai_role_ids?: string[]
          pre_close_minutes?: number
          reminder_1_min?: number
          reminder_2_min?: number
          reminder_enabled?: boolean
          reminder_minutes?: number | null
          session_name?: string
          skip_until?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      sessions: {
        Row: {
          allowed_role_id: string | null
          auto_close_at: string | null
          cancelled: boolean
          channel_id: string | null
          description: string | null
          eligible_member_ids: string[]
          ended_at: string | null
          guild_id: string
          id: string
          is_active: boolean
          message_id: string | null
          phai_role_ids: string[] | null
          role_name: string
          session_name: string
          started_at: string
          started_by: string
        }
        Insert: {
          allowed_role_id?: string | null
          auto_close_at?: string | null
          cancelled?: boolean
          channel_id?: string | null
          description?: string | null
          eligible_member_ids?: string[]
          ended_at?: string | null
          guild_id: string
          id?: string
          is_active?: boolean
          message_id?: string | null
          phai_role_ids?: string[] | null
          role_name?: string
          session_name: string
          started_at?: string
          started_by: string
        }
        Update: {
          allowed_role_id?: string | null
          auto_close_at?: string | null
          cancelled?: boolean
          channel_id?: string | null
          description?: string | null
          eligible_member_ids?: string[]
          ended_at?: string | null
          guild_id?: string
          id?: string
          is_active?: boolean
          message_id?: string | null
          phai_role_ids?: string[] | null
          role_name?: string
          session_name?: string
          started_at?: string
          started_by?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      advisory_unlock: {
        Args: { key1: number; key2: number }
        Returns: boolean
      }
      try_advisory_lock: {
        Args: { key1: number; key2: number }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
